name: Build Docker image and publish GHCR
concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.ref }}

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: ${{ runner.temp }}/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build production image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: |
                      ghcr.io/munezaclovis/mkcert:latest
                      ghcr.io/munezaclovi/mkcert:${{ github.sha }}
                  cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
                  cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

            - name: Move cache
              run: |
                  rm -rf ${{ runner.temp }}/.buildx-cache
                  mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
